#include <sdkcc/compiler/backend/c/generator.hpp>

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <set>
#include <stdexcept>
#include <string>
#include <variant>

namespace sdkcc::compiler::backend::c {
namespace {

std::string upper(std::string_view input) {
  std::string result;
  result.reserve(input.size());
  for (const char source_byte : input) {
    const auto byte = static_cast<unsigned char>(source_byte);
    result.push_back(static_cast<char>(std::toupper(byte)));
  }
  return result;
}

std::string model_base(const CodegenPlan &plan, TypeId type) {
  return plan.library + '_' + std::string{plan.type_name(type)};
}

std::string model_type(const CodegenPlan &plan, TypeId type) {
  return model_base(plan, type) + "_t";
}

std::string input_type(const CodegenPlan &plan, TypeId type) {
  return model_base(plan, type) + "_input_t";
}

std::string endpoint_base(const CodegenPlan &plan, EndpointId endpoint) {
  return plan.library + '_' + std::string{plan.endpoint_name(endpoint)};
}

const nair::PrimitiveType &primitive(const nair::Module &module, TypeId id) {
  const auto *value = std::get_if<nair::PrimitiveType>(&module.type(id).body);
  if (value == nullptr) {
    throw std::logic_error{"Milestone 1 field is not primitive"};
  }
  return *value;
}

std::string c_value_type(const nair::Module &module, TypeId id,
                         bool owned_string) {
  switch (primitive(module, id).kind) {
  case nair::PrimitiveKind::string:
    return owned_string ? "sdkcc_owned_string_t" : "sdkcc_string_view_t";
  case nair::PrimitiveKind::integer:
    return "int64_t";
  case nair::PrimitiveKind::boolean:
    return "bool";
  }
  throw std::logic_error{"unknown primitive kind"};
}

std::set<TypeId> request_types(const nair::Module &module) {
  std::set<TypeId> result;
  for (const auto &endpoint : module.endpoints()) {
    if (endpoint.request_body) {
      result.emplace(endpoint.request_body->type);
    }
  }
  return result;
}

std::set<TypeId> response_types(const nair::Module &module) {
  std::set<TypeId> result;
  for (const auto &endpoint : module.endpoints()) {
    result.emplace(endpoint.response.type);
  }
  return result;
}

void emit_model(CodeWriter &writer, const nair::Module &module,
                const CodegenPlan &plan, TypeId type_id, bool input) {
  const auto &structure = std::get<nair::StructType>(module.type(type_id).body);
  const std::string base =
      input ? model_base(plan, type_id) + "_input" : model_base(plan, type_id);
  writer.line("typedef struct " + base + " {");
  writer.indent();
  if (structure.fields.empty()) {
    writer.line("uint8_t _reserved;");
  }
  for (std::size_t index = 0U; index < structure.fields.size(); ++index) {
    const auto &field = structure.fields[index];
    const auto name = std::string{plan.field_name(type_id, index)};
    if (!field.required) {
      writer.line("bool has_" + name + ";");
    }
    writer.line(c_value_type(module, field.type, !input) + ' ' + name + ";");
  }
  writer.dedent();
  writer.line("} " +
              (input ? input_type(plan, type_id) : model_type(plan, type_id)) +
              ";");
  writer.line();
}

std::string generate_header(const nair::Module &module,
                            const CodegenPlan &plan) {
  CodeWriter writer;
  const std::string guard = upper(plan.library) + "_SDK_H";
  const std::string api = upper(plan.library) + "_API";
  writer.line("/* Generated by sdkcc. Do not edit. */");
  writer.line("#ifndef " + guard);
  writer.line("#define " + guard);
  writer.line();
  writer.line("#include <sdkcc/sdkcc.h>");
  writer.line();
  writer.line("#if defined(_WIN32)");
  writer.line("#  if defined(" + upper(plan.library) + "_STATIC)");
  writer.line("#    define " + api);
  writer.line("#  elif defined(" + upper(plan.library) + "_BUILDING_LIBRARY)");
  writer.line("#    define " + api + " __declspec(dllexport)");
  writer.line("#  else");
  writer.line("#    define " + api + " __declspec(dllimport)");
  writer.line("#  endif");
  writer.line("#elif defined(__GNUC__) || defined(__clang__)");
  writer.line("#  define " + api + " __attribute__((visibility(\"default\")))");
  writer.line("#else");
  writer.line("#  define " + api);
  writer.line("#endif");
  writer.line();
  writer.line("#ifdef __cplusplus");
  writer.line("extern \"C\" {");
  writer.line("#endif");
  writer.line();
  writer.line("typedef struct " + plan.library + "_client " + plan.library +
              "_client_t;");
  writer.line();
  writer.line("typedef struct " + plan.library + "_config {");
  writer.indent();
  writer.line("sdkcc_string_view_t base_url;");
  if (module.api_key_auth) {
    writer.line("sdkcc_string_view_t api_key;");
  }
  writer.line("sdkcc_allocator_t allocator;");
  writer.line("sdkcc_transport_t transport;");
  writer.dedent();
  writer.line("} " + plan.library + "_config_t;");
  writer.line();
  for (const TypeId type : plan.emitted_types) {
    emit_model(writer, module, plan, type, false);
  }
  for (const TypeId type : request_types(module)) {
    emit_model(writer, module, plan, type, true);
  }
  writer.line(api + " sdkcc_status_t " + plan.library +
              "_v1_client_create(const " + plan.library +
              "_config_t *config, " + plan.library +
              "_client_t **out_client, sdkcc_error_t *error);");
  writer.line(api + " void " + plan.library + "_v1_client_destroy(" +
              plan.library + "_client_t *client);");
  writer.line();
  for (const TypeId type : plan.emitted_types) {
    writer.line(api + " void " + plan.library + "_v1_model_" +
                std::string{plan.type_name(type)} + "_reset(" +
                model_type(plan, type) + " *value);");
  }
  writer.line();
  for (const EndpointId endpoint_id : plan.emitted_endpoints) {
    const auto &endpoint = module.endpoint(endpoint_id);
    const auto base = endpoint_base(plan, endpoint_id);
    writer.line("typedef struct " + base + "_params {");
    writer.indent();
    if (endpoint.parameters.empty() && !endpoint.request_body) {
      writer.line("uint8_t _reserved;");
    }
    for (std::size_t index = 0U; index < endpoint.parameters.size(); ++index) {
      const auto &parameter = endpoint.parameters[index];
      const auto name = std::string{plan.parameter_name(endpoint_id, index)};
      if (!parameter.required) {
        writer.line("bool has_" + name + ";");
      }
      writer.line(c_value_type(module, parameter.type, false) + ' ' + name +
                  ";");
    }
    if (endpoint.request_body) {
      writer.line("const " + input_type(plan, endpoint.request_body->type) +
                  " *body;");
    }
    writer.dedent();
    writer.line("} " + base + "_params_t;");
    writer.line("typedef " + model_type(plan, endpoint.response.type) + ' ' +
                base + "_response_t;");
    writer.line(api + " sdkcc_status_t " + plan.library + "_v1_" +
                std::string{plan.endpoint_name(endpoint_id)} + "(" +
                plan.library + "_client_t *client, const " + base +
                "_params_t *params, " + base +
                "_response_t *out_response, sdkcc_error_t *error);");
    writer.line();
  }
  writer.line("#ifdef __cplusplus");
  writer.line("}");
  writer.line("#endif");
  writer.line();
  writer.line("#endif");
  return std::move(writer).take();
}

void emit_status_call(CodeWriter &writer, std::string expression) {
  writer.line("status = " + std::move(expression) + ";");
  writer.line("if (status != SDKCC_OK) {");
  writer.indent();
  writer.line("goto cleanup;");
  writer.dedent();
  writer.line("}");
}

void emit_json_writer(CodeWriter &writer, const nair::Module &module,
                      TypeId type, std::string expression,
                      std::string_view buffer_expression) {
  std::string function;
  switch (primitive(module, type).kind) {
  case nair::PrimitiveKind::string:
    function = "sdkcc_v1_json_write_string";
    break;
  case nair::PrimitiveKind::integer:
    function = "sdkcc_v1_json_write_i64";
    break;
  case nair::PrimitiveKind::boolean:
    function = "sdkcc_v1_json_write_bool";
    break;
  }
  emit_status_call(writer, function + "(" + std::string{buffer_expression} +
                               ", " + std::move(expression) + ", error)");
}

void emit_input_serializer(CodeWriter &writer, const nair::Module &module,
                           const CodegenPlan &plan, TypeId type_id) {
  const auto &structure = std::get<nair::StructType>(module.type(type_id).body);
  const auto function = "serialize_" + model_base(plan, type_id) + "_input";
  writer.line("static sdkcc_status_t " + function + "(const " +
              input_type(plan, type_id) +
              " *value, sdkcc_buffer_t *buffer, sdkcc_error_t *error) {");
  writer.indent();
  writer.line("if (value == NULL || buffer == NULL) {");
  writer.indent();
  writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_INVALID_ARGUMENT, "
              "SDKCC_ERROR_ARGUMENT, \"invalid request body\");");
  writer.dedent();
  writer.line("}");
  writer.line("sdkcc_status_t status = SDKCC_OK;");
  if (!structure.fields.empty()) {
    writer.line("bool first = true;");
  }
  emit_status_call(writer,
                   "sdkcc_v1_buffer_append_byte(buffer, (uint8_t)'{', error)");
  for (std::size_t index = 0U; index < structure.fields.size(); ++index) {
    const auto &field = structure.fields[index];
    const auto name = std::string{plan.field_name(type_id, index)};
    if (!field.required) {
      writer.line("if (value->has_" + name + ") {");
      writer.indent();
    }
    writer.line("if (!first) {");
    writer.indent();
    emit_status_call(
        writer, "sdkcc_v1_buffer_append_byte(buffer, (uint8_t)',', error)");
    writer.dedent();
    writer.line("}");
    writer.line("first = false;");
    emit_status_call(writer,
                     "sdkcc_v1_json_write_string(buffer, SDKCC_STR_LITERAL(" +
                         c_string_literal(module.string(field.wire_name)) +
                         "), error)");
    emit_status_call(
        writer, "sdkcc_v1_buffer_append_byte(buffer, (uint8_t)':', error)");
    emit_json_writer(writer, module, field.type, "value->" + name, "buffer");
    if (!field.required) {
      writer.dedent();
      writer.line("}");
    }
  }
  emit_status_call(writer,
                   "sdkcc_v1_buffer_append_byte(buffer, (uint8_t)'}', error)");
  writer.line("return SDKCC_OK;");
  writer.line("cleanup:");
  writer.line("return status;");
  writer.dedent();
  writer.line("}");
  writer.line();
}

std::string json_decoder(nair::PrimitiveKind kind) {
  switch (kind) {
  case nair::PrimitiveKind::string:
    return "sdkcc_v1_json_value_to_owned_string";
  case nair::PrimitiveKind::integer:
    return "sdkcc_v1_json_value_to_i64";
  case nair::PrimitiveKind::boolean:
    return "sdkcc_v1_json_value_to_bool";
  }
  throw std::logic_error{"unknown primitive kind"};
}

void emit_response_parser(CodeWriter &writer, const nair::Module &module,
                          const CodegenPlan &plan, TypeId type_id) {
  const auto &structure = std::get<nair::StructType>(module.type(type_id).body);
  const auto base = model_base(plan, type_id);
  writer.line("typedef struct parse_" + base + "_context {");
  writer.indent();
  writer.line(model_type(plan, type_id) + " *value;");
  writer.line("const sdkcc_allocator_t *allocator;");
  for (std::size_t index = 0U; index < structure.fields.size(); ++index) {
    writer.line("bool seen_" + std::to_string(index) + ";");
  }
  writer.dedent();
  writer.line("} parse_" + base + "_context_t;");
  writer.line();
  writer.line("static sdkcc_status_t visit_" + base +
              "(void *opaque, sdkcc_string_view_t key, "
              "sdkcc_json_value_t json, sdkcc_error_t *error) {");
  writer.indent();
  writer.line("parse_" + base + "_context_t *const context = opaque;");
  for (std::size_t index = 0U; index < structure.fields.size(); ++index) {
    const auto &field = structure.fields[index];
    const auto name = std::string{plan.field_name(type_id, index)};
    writer.line("if (sdkcc_v1_json_key_equals(key, SDKCC_STR_LITERAL(" +
                c_string_literal(module.string(field.wire_name)) + "))) {");
    writer.indent();
    writer.line("if (context->seen_" + std::to_string(index) + ") {");
    writer.indent();
    writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_SCHEMA, "
                "SDKCC_ERROR_SERIALIZATION, \"duplicate response field\");");
    writer.dedent();
    writer.line("}");
    writer.line("context->seen_" + std::to_string(index) + " = true;");
    const auto kind = primitive(module, field.type).kind;
    if (kind == nair::PrimitiveKind::string) {
      writer.line("return " + json_decoder(kind) +
                  "(json, context->allocator, &context->value->" + name +
                  ", error);");
    } else {
      writer.line("return " + json_decoder(kind) + "(json, &context->value->" +
                  name + ", error);");
    }
    writer.dedent();
    writer.line("}");
  }
  writer.line("(void)context;");
  writer.line("(void)json;");
  writer.line("return SDKCC_OK;");
  writer.dedent();
  writer.line("}");
  writer.line();
  writer.line(
      "static sdkcc_status_t parse_" + base +
      "(sdkcc_buffer_view_t json, const sdkcc_allocator_t *allocator, " +
      model_type(plan, type_id) + " *out, sdkcc_error_t *error) {");
  writer.indent();
  writer.line(plan.library + "_v1_model_" +
              std::string{plan.type_name(type_id)} + "_reset(out);");
  writer.line("parse_" + base + "_context_t context = {");
  writer.indent();
  writer.line(".value = out,");
  writer.line(".allocator = allocator,");
  writer.dedent();
  writer.line("};");
  writer.line("sdkcc_status_t status = sdkcc_v1_json_object_visit("
              "json, visit_" +
              base + ", &context, error);");
  writer.line("if (status != SDKCC_OK) {");
  writer.indent();
  writer.line(plan.library + "_v1_model_" +
              std::string{plan.type_name(type_id)} + "_reset(out);");
  writer.line("return status;");
  writer.dedent();
  writer.line("}");
  for (std::size_t index = 0U; index < structure.fields.size(); ++index) {
    if (structure.fields[index].required) {
      writer.line("if (!context.seen_" + std::to_string(index) + ") {");
      writer.indent();
      writer.line(plan.library + "_v1_model_" +
                  std::string{plan.type_name(type_id)} + "_reset(out);");
      writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_SCHEMA, "
                  "SDKCC_ERROR_SERIALIZATION, "
                  "\"required response field is missing\");");
      writer.dedent();
      writer.line("}");
    } else {
      writer.line("out->has_" + std::string{plan.field_name(type_id, index)} +
                  " = context.seen_" + std::to_string(index) + ";");
    }
  }
  writer.line("return SDKCC_OK;");
  writer.dedent();
  writer.line("}");
  writer.line();
}

void emit_model_reset(CodeWriter &writer, const nair::Module &module,
                      const CodegenPlan &plan, TypeId type_id) {
  const auto &structure = std::get<nair::StructType>(module.type(type_id).body);
  writer.line("void " + plan.library + "_v1_model_" +
              std::string{plan.type_name(type_id)} + "_reset(" +
              model_type(plan, type_id) + " *value) {");
  writer.indent();
  writer.line("if (value == NULL) {");
  writer.indent();
  writer.line("return;");
  writer.dedent();
  writer.line("}");
  for (std::size_t index = 0U; index < structure.fields.size(); ++index) {
    if (primitive(module, structure.fields[index].type).kind ==
        nair::PrimitiveKind::string) {
      writer.line("sdkcc_v1_owned_string_reset(&value->" +
                  std::string{plan.field_name(type_id, index)} + ");");
    }
  }
  writer.line("*value = (" + model_type(plan, type_id) + "){0};");
  writer.dedent();
  writer.line("}");
  writer.line();
}

void emit_uri_value(CodeWriter &writer, const nair::Module &module, TypeId type,
                    std::string expression) {
  switch (primitive(module, type).kind) {
  case nair::PrimitiveKind::string:
    emit_status_call(writer, "sdkcc_v1_uri_encode_append(&url, " + expression +
                                 ", error)");
    return;
  case nair::PrimitiveKind::integer:
    emit_status_call(writer, "sdkcc_v1_json_write_i64(&url, " + expression +
                                 ", error)");
    return;
  case nair::PrimitiveKind::boolean:
    emit_status_call(writer, "sdkcc_v1_json_write_bool(&url, " + expression +
                                 ", error)");
    return;
  }
}

std::size_t parameter_index(const nair::Module &module,
                            const nair::Endpoint &endpoint,
                            std::string_view wire_name,
                            nair::ParameterLocation location) {
  for (std::size_t index = 0U; index < endpoint.parameters.size(); ++index) {
    if (endpoint.parameters[index].location == location &&
        module.string(endpoint.parameters[index].wire_name) == wire_name) {
      return index;
    }
  }
  throw std::logic_error{"path parameter missing after validation"};
}

void emit_path(CodeWriter &writer, const nair::Module &module,
               const CodegenPlan &plan, const nair::Endpoint &endpoint) {
  const auto path = module.string(endpoint.path);
  std::size_t cursor = 0U;
  while (cursor < path.size()) {
    const auto open = path.find('{', cursor);
    const auto end = open == std::string_view::npos ? path.size() : open;
    if (end != cursor) {
      emit_status_call(
          writer, "sdkcc_v1_buffer_append_string(&url, SDKCC_STR_LITERAL(" +
                      c_string_literal(path.substr(cursor, end - cursor)) +
                      "), error)");
    }
    if (open == std::string_view::npos) {
      break;
    }
    const auto close = path.find('}', open + 1U);
    const auto wire_name = path.substr(open + 1U, close - open - 1U);
    const auto index = parameter_index(module, endpoint, wire_name,
                                       nair::ParameterLocation::path);
    const auto &parameter = endpoint.parameters[index];
    emit_uri_value(writer, module, parameter.type,
                   "params->" +
                       std::string{plan.parameter_name(endpoint.id, index)});
    cursor = close + 1U;
  }
}

void emit_query(CodeWriter &writer, const nair::Module &module,
                const CodegenPlan &plan, const nair::Endpoint &endpoint) {
  if (std::ranges::none_of(endpoint.parameters, [](const auto &parameter) {
        return parameter.location == nair::ParameterLocation::query;
      })) {
    return;
  }
  writer.line("bool query_started = false;");
  for (std::size_t index = 0U; index < endpoint.parameters.size(); ++index) {
    const auto &parameter = endpoint.parameters[index];
    if (parameter.location != nair::ParameterLocation::query) {
      continue;
    }
    const auto name = std::string{plan.parameter_name(endpoint.id, index)};
    if (!parameter.required) {
      writer.line("if (params->has_" + name + ") {");
      writer.indent();
    }
    emit_status_call(writer, "sdkcc_v1_buffer_append_byte(&url, "
                             "(uint8_t)(query_started ? '&' : '?'), error)");
    writer.line("query_started = true;");
    emit_status_call(writer,
                     "sdkcc_v1_uri_encode_append(&url, SDKCC_STR_LITERAL(" +
                         c_string_literal(module.string(parameter.wire_name)) +
                         "), error)");
    emit_status_call(writer,
                     "sdkcc_v1_buffer_append_byte(&url, (uint8_t)'=', error)");
    emit_uri_value(writer, module, parameter.type, "params->" + name);
    if (!parameter.required) {
      writer.dedent();
      writer.line("}");
    }
  }
}

void emit_endpoint(CodeWriter &writer, const nair::Module &module,
                   const CodegenPlan &plan, EndpointId endpoint_id) {
  const auto &endpoint = module.endpoint(endpoint_id);
  const auto base = endpoint_base(plan, endpoint_id);
  writer.line("sdkcc_status_t " + plan.library + "_v1_" +
              std::string{plan.endpoint_name(endpoint_id)} + "(" +
              plan.library + "_client_t *client, const " + base +
              "_params_t *params, " + base +
              "_response_t *out_response, sdkcc_error_t *error) {");
  writer.indent();
  writer.line("sdkcc_status_t status = SDKCC_OK;");
  writer.line("sdkcc_request_t *request = NULL;");
  writer.line("sdkcc_response_t response = {0};");
  writer.line("sdkcc_buffer_t url = {0};");
  if (endpoint.request_body) {
    writer.line("sdkcc_buffer_t body = {0};");
  }
  writer.line("if (error != NULL) {");
  writer.indent();
  writer.line("sdkcc_v1_error_reset(error);");
  writer.dedent();
  writer.line("}");
  writer.line(
      "if (client == NULL || params == NULL || out_response == NULL) {");
  writer.indent();
  writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_INVALID_ARGUMENT, "
              "SDKCC_ERROR_ARGUMENT, \"invalid endpoint arguments\");");
  writer.dedent();
  writer.line("}");
  if (endpoint.request_body && endpoint.request_body->required) {
    writer.line("if (params->body == NULL) {");
    writer.indent();
    writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_INVALID_ARGUMENT, "
                "SDKCC_ERROR_ARGUMENT, \"required request body is null\");");
    writer.dedent();
    writer.line("}");
  }
  writer.line(plan.library + "_v1_model_" +
              std::string{plan.type_name(endpoint.response.type)} +
              "_reset(out_response);");
  emit_status_call(writer, "sdkcc_v1_buffer_init(&url, &client->allocator)");
  emit_status_call(
      writer, "sdkcc_v1_request_create(&client->allocator, &request, error)");
  emit_status_call(writer,
                   "sdkcc_v1_buffer_append_string(&url, "
                   "sdkcc_v1_owned_string_view(&client->base_url), error)");
  emit_path(writer, module, plan, endpoint);
  emit_query(writer, module, plan, endpoint);
  emit_status_call(
      writer, "sdkcc_v1_request_set_url("
              "request, (sdkcc_string_view_t){.data = (const char *)url.data, "
              ".len = url.len}, error)");
  const std::string method = endpoint.method == nair::HttpMethod::get
                                 ? "SDKCC_HTTP_GET"
                                 : "SDKCC_HTTP_POST";
  emit_status_call(writer, "sdkcc_v1_request_set_method(request, " + method +
                               ", error)");
  if (endpoint.authenticated) {
    emit_status_call(
        writer,
        "sdkcc_v1_request_add_header("
        "request, SDKCC_STR_LITERAL(" +
            c_string_literal(module.string(module.api_key_auth->wire_name)) +
            "), sdkcc_v1_owned_string_view(&client->api_key), error)");
  }
  if (endpoint.request_body) {
    writer.line("if (params->body != NULL) {");
    writer.indent();
    emit_status_call(writer, "sdkcc_v1_buffer_init(&body, &client->allocator)");
    emit_status_call(writer, "serialize_" +
                                 model_base(plan, endpoint.request_body->type) +
                                 "_input(params->body, &body, error)");
    emit_status_call(writer, "sdkcc_v1_request_add_header("
                             "request, SDKCC_STR_LITERAL(\"Content-Type\"), "
                             "SDKCC_STR_LITERAL(\"application/json\"), error)");
    emit_status_call(writer, "sdkcc_v1_request_set_body("
                             "request, sdkcc_v1_buffer_view(&body), error)");
    writer.dedent();
    writer.line("}");
  }
  emit_status_call(writer,
                   "sdkcc_v1_transport_send(&client->transport, request, "
                   "&client->allocator, &response, error)");
  writer.line("if (response.http_status != " +
              std::to_string(endpoint.response.http_status) + ") {");
  writer.indent();
  writer.line("status = sdkcc_v1_error_set(error, SDKCC_ERR_HTTP, "
              "SDKCC_ERROR_PROTOCOL, \"unexpected HTTP response status\");");
  writer.line("if (error != NULL) {");
  writer.indent();
  writer.line("error->http_status = response.http_status;");
  writer.dedent();
  writer.line("}");
  writer.line("goto cleanup;");
  writer.dedent();
  writer.line("}");
  emit_status_call(
      writer, "parse_" + model_base(plan, endpoint.response.type) +
                  "(sdkcc_v1_buffer_view(&response.body), &client->allocator, "
                  "out_response, error)");
  writer.line("cleanup:");
  writer.line("sdkcc_v1_response_reset(&response);");
  writer.line("sdkcc_v1_request_destroy(request);");
  writer.line("sdkcc_v1_buffer_reset(&url);");
  if (endpoint.request_body) {
    writer.line("sdkcc_v1_buffer_reset(&body);");
  }
  writer.line("return status;");
  writer.dedent();
  writer.line("}");
  writer.line();
}

void emit_client(CodeWriter &writer, const nair::Module &module,
                 const CodegenPlan &plan) {
  writer.line("sdkcc_status_t " + plan.library + "_v1_client_create(const " +
              plan.library + "_config_t *config, " + plan.library +
              "_client_t **out_client, sdkcc_error_t *error) {");
  writer.indent();
  writer.line("if (error != NULL) {");
  writer.indent();
  writer.line("sdkcc_v1_error_reset(error);");
  writer.dedent();
  writer.line("}");
  writer.line("if (config == NULL || out_client == NULL) {");
  writer.indent();
  writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_INVALID_ARGUMENT, "
              "SDKCC_ERROR_ARGUMENT, \"invalid client configuration\");");
  writer.dedent();
  writer.line("}");
  writer.line("*out_client = NULL;");
  writer.line("sdkcc_allocator_t allocator = config->allocator;");
  writer.line("const bool allocator_supplied = allocator.alloc != NULL || "
              "allocator.realloc != NULL || allocator.free != NULL;");
  writer.line("if (!allocator_supplied) {");
  writer.indent();
  writer.line("allocator = sdkcc_v1_system_allocator();");
  writer.dedent();
  writer.line("} else if (!sdkcc_v1_allocator_is_valid(&allocator)) {");
  writer.indent();
  writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_INVALID_ARGUMENT, "
              "SDKCC_ERROR_ARGUMENT, \"allocator vtable is incomplete\");");
  writer.dedent();
  writer.line("}");
  writer.line("if (config->transport.vtable == NULL || "
              "config->transport.vtable->abi_version != SDKCC_ABI_VERSION || "
              "config->transport.vtable->send == NULL) {");
  writer.indent();
  writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_INVALID_ARGUMENT, "
              "SDKCC_ERROR_ARGUMENT, \"transport vtable is invalid\");");
  writer.dedent();
  writer.line("}");
  writer.line("sdkcc_string_view_t base_url = config->base_url;");
  if (!module.string(module.base_url).empty()) {
    writer.line("if (base_url.data == NULL || base_url.len == 0U) {");
    writer.indent();
    writer.line("base_url = SDKCC_STR_LITERAL(" +
                c_string_literal(module.string(module.base_url)) + ");");
    writer.dedent();
    writer.line("}");
  }
  writer.line("while (base_url.len > 0U && "
              "base_url.data[base_url.len - 1U] == '/') {");
  writer.indent();
  writer.line("--base_url.len;");
  writer.dedent();
  writer.line("}");
  writer.line("if (base_url.data == NULL || base_url.len == 0U) {");
  writer.indent();
  writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_INVALID_ARGUMENT, "
              "SDKCC_ERROR_ARGUMENT, \"base URL is empty\");");
  writer.dedent();
  writer.line("}");
  if (module.api_key_auth) {
    writer.line(
        "if (config->api_key.data == NULL || config->api_key.len == 0U) {");
    writer.indent();
    writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_AUTH, "
                "SDKCC_ERROR_ARGUMENT, \"API key is empty\");");
    writer.dedent();
    writer.line("}");
  }
  writer.line(plan.library +
              "_client_t *const client = allocator.alloc("
              "allocator.ctx, sizeof(*client), alignof(" +
              plan.library + "_client_t));");
  writer.line("if (client == NULL) {");
  writer.indent();
  writer.line("return sdkcc_v1_error_set(error, SDKCC_ERR_OOM, "
              "SDKCC_ERROR_MEMORY, \"client allocation failed\");");
  writer.dedent();
  writer.line("}");
  writer.line("*client = (" + plan.library +
              "_client_t){.allocator = allocator, "
              ".transport = config->transport};");
  writer.line("sdkcc_status_t status = sdkcc_v1_owned_string_copy("
              "base_url, &allocator, &client->base_url, error);");
  writer.line("if (status != SDKCC_OK) {");
  writer.indent();
  writer.line(plan.library + "_v1_client_destroy(client);");
  writer.line("return status;");
  writer.dedent();
  writer.line("}");
  if (module.api_key_auth) {
    writer.line("status = sdkcc_v1_owned_string_copy("
                "config->api_key, &allocator, &client->api_key, error);");
    writer.line("if (status != SDKCC_OK) {");
    writer.indent();
    writer.line(plan.library + "_v1_client_destroy(client);");
    writer.line("return status;");
    writer.dedent();
    writer.line("}");
  }
  writer.line("*out_client = client;");
  writer.line("return SDKCC_OK;");
  writer.dedent();
  writer.line("}");
  writer.line();
  writer.line("void " + plan.library + "_v1_client_destroy(" + plan.library +
              "_client_t *client) {");
  writer.indent();
  writer.line("if (client == NULL) {");
  writer.indent();
  writer.line("return;");
  writer.dedent();
  writer.line("}");
  writer.line("const sdkcc_allocator_t allocator = client->allocator;");
  writer.line("sdkcc_v1_owned_string_reset(&client->base_url);");
  if (module.api_key_auth) {
    writer.line("sdkcc_v1_owned_string_reset(&client->api_key);");
  }
  writer.line("allocator.free(allocator.ctx, client, sizeof(*client), "
              "alignof(" +
              plan.library + "_client_t));");
  writer.dedent();
  writer.line("}");
  writer.line();
}

std::string generate_source(const nair::Module &module,
                            const CodegenPlan &plan) {
  CodeWriter writer;
  writer.line("/* Generated by sdkcc. Do not edit. */");
  writer.line("#include <" + plan.library + "/" + plan.library + ".h>");
  writer.line();
  writer.line("#include <stdalign.h>");
  writer.line();
  writer.line("struct " + plan.library + "_client {");
  writer.indent();
  writer.line("sdkcc_allocator_t allocator;");
  writer.line("sdkcc_transport_t transport;");
  writer.line("sdkcc_owned_string_t base_url;");
  if (module.api_key_auth) {
    writer.line("sdkcc_owned_string_t api_key;");
  }
  writer.dedent();
  writer.line("};");
  writer.line();
  for (const TypeId type : request_types(module)) {
    emit_input_serializer(writer, module, plan, type);
  }
  for (const TypeId type : response_types(module)) {
    emit_response_parser(writer, module, plan, type);
  }
  for (const TypeId type : plan.emitted_types) {
    emit_model_reset(writer, module, plan, type);
  }
  emit_client(writer, module, plan);
  for (const EndpointId endpoint : plan.emitted_endpoints) {
    emit_endpoint(writer, module, plan, endpoint);
  }
  return std::move(writer).take();
}

std::string generate_cmake(const CodegenPlan &plan, bool include_cpp) {
  CodeWriter writer;
  writer.line("cmake_minimum_required(VERSION 3.28)");
  writer.line("project(" + plan.library + " VERSION 0.1.0 LANGUAGES C" +
              (include_cpp ? " CXX)" : ")"));
  writer.line("include(GNUInstallDirs)");
  writer.line("include(CMakePackageConfigHelpers)");
  writer.line("if(NOT TARGET sdkcc::runtime)");
  writer.indent();
  writer.line("find_package(sdkcc CONFIG REQUIRED)");
  writer.dedent();
  writer.line("endif()");
  writer.line("add_library(" + plan.library + " src/" + plan.library + ".c)");
  writer.line("add_library(" + plan.library + "::" + plan.library + " ALIAS " +
              plan.library + ")");
  writer.line("target_compile_features(" + plan.library + " PUBLIC c_std_23)");
  writer.line("target_compile_definitions(" + plan.library + " PRIVATE " +
              upper(plan.library) + "_BUILDING_LIBRARY=1)");
  writer.line("if(NOT BUILD_SHARED_LIBS)");
  writer.indent();
  writer.line("target_compile_definitions(" + plan.library + " PUBLIC " +
              upper(plan.library) + "_STATIC=1)");
  writer.dedent();
  writer.line("endif()");
  writer.line("target_include_directories(" + plan.library + " PUBLIC");
  writer.indent();
  writer.line("$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>");
  writer.line("$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>");
  writer.dedent();
  writer.line(")");
  writer.line("target_link_libraries(" + plan.library +
              " PUBLIC sdkcc::runtime)");
  writer.line("if(TARGET sdkcc_warnings)");
  writer.indent();
  writer.line("target_link_libraries(" + plan.library +
              " PRIVATE $<BUILD_INTERFACE:sdkcc_warnings> "
              "$<BUILD_INTERFACE:sdkcc_sanitizers>)");
  writer.dedent();
  writer.line("endif()");
  writer.line("set_target_properties(" + plan.library +
              " PROPERTIES C_VISIBILITY_PRESET hidden "
              "POSITION_INDEPENDENT_CODE ON)");
  if (include_cpp) {
    writer.line("add_library(" + plan.library + "_cpp INTERFACE)");
    writer.line("add_library(" + plan.library + "::cpp ALIAS " + plan.library +
                "_cpp)");
    writer.line("target_compile_features(" + plan.library +
                "_cpp INTERFACE cxx_std_23)");
    writer.line("target_include_directories(" + plan.library +
                "_cpp INTERFACE");
    writer.indent();
    writer.line("$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>");
    writer.line("$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>");
    writer.dedent();
    writer.line(")");
    writer.line("target_link_libraries(" + plan.library + "_cpp INTERFACE " +
                plan.library + " sdkcc::cpp)");
  }
  writer.line("install(TARGETS " + plan.library +
              (include_cpp ? " " + plan.library + "_cpp" : "") + " EXPORT " +
              plan.library + "Targets)");
  writer.line("install(DIRECTORY include/ DESTINATION "
              "${CMAKE_INSTALL_INCLUDEDIR})");
  writer.line("install(EXPORT " + plan.library + "Targets FILE " +
              plan.library + "Targets.cmake NAMESPACE " + plan.library +
              ":: DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/" + plan.library +
              ")");
  writer.line("configure_package_config_file(cmake/" + plan.library +
              "Config.cmake.in ${CMAKE_CURRENT_BINARY_DIR}/" + plan.library +
              "Config.cmake INSTALL_DESTINATION "
              "${CMAKE_INSTALL_LIBDIR}/cmake/" +
              plan.library + ")");
  writer.line("write_basic_package_version_file("
              "${CMAKE_CURRENT_BINARY_DIR}/" +
              plan.library +
              "ConfigVersion.cmake VERSION ${PROJECT_VERSION} "
              "COMPATIBILITY SameMajorVersion)");
  writer.line("configure_file(cmake/" + plan.library +
              ".pc.in ${CMAKE_CURRENT_BINARY_DIR}/" + plan.library +
              ".pc @ONLY)");
  writer.line("install(FILES ${CMAKE_CURRENT_BINARY_DIR}/" + plan.library +
              "Config.cmake ${CMAKE_CURRENT_BINARY_DIR}/" + plan.library +
              "ConfigVersion.cmake DESTINATION "
              "${CMAKE_INSTALL_LIBDIR}/cmake/" +
              plan.library + ")");
  writer.line("install(FILES ${CMAKE_CURRENT_BINARY_DIR}/" + plan.library +
              ".pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)");
  return std::move(writer).take();
}

std::string generate_config_in(const CodegenPlan &plan) {
  return "@PACKAGE_INIT@\ninclude(CMakeFindDependencyMacro)\n"
         "find_dependency(sdkcc CONFIG)\ninclude(\"${CMAKE_CURRENT_LIST_DIR}/" +
         plan.library + "Targets.cmake\")\n";
}

std::string generate_pc_in(const CodegenPlan &plan) {
  return "prefix=@CMAKE_INSTALL_PREFIX@\n"
         "exec_prefix=${prefix}\n"
         "libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@\n"
         "includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@\n\n"
         "Name: " +
         plan.library +
         "\nDescription: Native SDK generated by sdkcc\n"
         "Version: @PROJECT_VERSION@\n"
         "Libs: -L${libdir} -l" +
         plan.library + "\nCflags: -I${includedir}\n";
}

} // namespace

std::vector<GeneratedFile> generate(const nair::Module &module,
                                    const CodegenPlan &plan,
                                    bool include_cpp_target) {
  return {
      {.relative_path = "CMakeLists.txt",
       .content = generate_cmake(plan, include_cpp_target)},
      {.relative_path = std::filesystem::path{"include"} / plan.library /
                        (plan.library + ".h"),
       .content = generate_header(module, plan)},
      {.relative_path = std::filesystem::path{"src"} / (plan.library + ".c"),
       .content = generate_source(module, plan)},
      {.relative_path =
           std::filesystem::path{"cmake"} / (plan.library + "Config.cmake.in"),
       .content = generate_config_in(plan)},
      {.relative_path =
           std::filesystem::path{"cmake"} / (plan.library + ".pc.in"),
       .content = generate_pc_in(plan)},
  };
}

} // namespace sdkcc::compiler::backend::c
